import './global.css';
import { UiLayout } from '@/components/ui/ui-layout';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { SolanaProvider } from '@/components/solana/solana-provider';
import { ReactQueryProvider } from './react-query-provider';

export const metadata = {
  title: 'apeboy',
  description: 'Generated by create-solana-dapp',
};

const links: { label: string; path: string }[] = [
  // { label: 'home', path: '/' },
  {
    label: '$apeboy',
    path: 'https://solscan.io/token/Gz8758urhVJfaZFbuGy2rgYSxbkf6qFUodEk9eY9SgUa',
  },
  { label: 'twitter', path: 'https://x.com/apeboyclub' },
  { label: 'tg', path: 'https://t.me/apeboycommunity' },
  { label: 'wp', path: 'https://docs.apeboysclub.site' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <UiLayout links={links}>{children}</UiLayout>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
